FusionIIIT/Fusion/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include('applications.globals.urls')),
    url(r'^eis/', include('applications.eis.urls',namespace='eis')),
    url(r'^mess/', include('applications.central_mess.urls')),
    url(r'^complaint/', include('applications.complaint_system.urls')),
    url(r'^healthcenter/', include('applications.health_center.urls')),
    url(r'^leave/', include('applications.leave.urls')),
    url(r'^placement/', include('applications.placement_cell.urls',namespace='placement')),
    url(r'^filetracking/', include('applications.filetracking.urls')),
    url(r'^spacs/', include('applications.scholarships.urls')),
    url(r'^visitorhostel/', include('applications.visitor_hostel.urls')),
    url(r'^office/', include('applications.office_module.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^finance/', include('applications.finance_accounts.urls')),
    url(r'^gymkhana/', include('applications.gymkhana.urls')),
    url(r'^library/', include('applications.library.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ocms/', include('applications.online_cms.urls')),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'^academic-procedures/', include('applications.academic_procedures.urls',
                                          namespace='procedures')),
    url(r'^aims/', include('applications.academic_information.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

FusionIIIT/applications/office_module/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name = 'office'

urlpatterns = [

    url(r'^officeOfDeanPnD/submit$',views.submitRequest,name='pWorkRequest'),
    url(r'^officeOfDeanPnD/action$',views.action,name='action'),
    url(r'^officeOfPurchaseOfficer/',views.officeOfPurchaseOfficer, name ='officeOfPurchaseOfficer'),
    url(r'^apply_purchase/', views.apply_purchase, name='apply_purchase'),
    url(r'^after_purchase/', views.after_purchase, name='after_purchase'),
    url(r'^officeOfRegistrar/$', views.officeOfRegistrar, name='officeOfRegistrar'),
    url(r'^officeOfDeanRSPC/$', views.officeOfDeanRSPC, name='officeOfDeanRSPC'),

    url(r'^officeOfDeanRSPC/submit/$',views.project_register,name='p_register'),
    url(r'^officeOfDeanRSPC/extention/$',views.project_extension,name='p_extension'),
    url(r'^officeOfDeanRSPC/close/$',views.project_closure,name='p_closure'),
    url(r'^officeOfDeanRSPC/reallocate/$',views.project_reallocation,name='p_reallocation'),
    url(r'^officeOfDeanRSPC/action/$',views.project_registration_permission,name='registration'),
    url(r'^officeOfDeanRSPC/extension/$',views.project_extension_permission,name='extension'),
    url(r'^officeOfDeanRSPC/closure/$',views.project_closure_permission,name='closure'),
    url(r'^officeOfDeanRSPC/reallocation/$',views.project_reallocation_permission,name='reallocation'),
    url(r'^officeOfDeanRSPC/forwarded/$',views.hod_action,name='hod_action'),
    url(r'^officeOfDeanRSPC/forwarded1/$',views.hod_closure,name='hod_closure'),
    url(r'^officeOfDeanRSPC/forwarded2/$',views.hod_extension,name='hod_extension'),
    url(r'^officeOfDeanRSPC/forwarded3/$',views.hod_allocation,name='hod_allocation'),
    url(r'^officeOfDeanRSPC/(?P<pr_id>[0-9]+)/$',views.pdf,name='pdf'),

    url(r'^eisModulenew/profile', views.eisModulenew, name='eisModulenew'),

    url(r'^officeOfDeanPnD/$', views.officeOfDeanPnD, name='officeOfDeanPnD'),
    url(r'^officeOfHOD/$', views.officeOfHOD, name='officeOfHOD'),
    url(r'^officeOfHOD/submit/$',views.teaching_form,name='teaching_form'),
    url(r'^officeOfHOD/work/$',views.hod_work,name='hod_work'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^deleteitem/(?P<id>[0-9]+)',views.delete_item, name='delete_item'),
    url(r'^deletevendor/(?P<id>[0-9]+)',views.delete_vendor, name='delete_vendor'),
    url(r'^editvendor/(?P<id>[0-9]+)',views.edit_vendor, name='edit_vendor'),
    url(r'^editvendor/office/officeOfPurchaseOfficer/edit/',views.edit,name='edit'),
    url(r'^edititem/(?P<id>[0-9]+)',views.edit_item, name='edit_item'),
    url(r'^edititem/office/officeOfPurchaseOfficer/edit1/',views.edit1,name='edit'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^directorOffice/$', views.directorOffice, name='directorOffice'),
    url(r'^directorOffice/appoint', views.appoint, name='appoint'),
    url(r'^directorOffice/meeting', views.meeting, name='meeting'),
    url(r'^officeOfRegistrar/upload/$', views.upload, name='upload'),
    url(r'^officeOfRegistrar/generalAdminForm/reject/$', csrf_exempt(views.admin_reject), name='admin_reject'),
    url(r'^officeOfDeanStudents/$', views.officeOfDeanStudents, name='officeOfDeanStudents'),
    url(r'^officeOfPurchaseOfficer/', views.officeOfPurchaseOfficr, name='officeOfPurchaseOfficer'),
    url(r'^officeOfRegistrar/', views.officeOfRegistrar, name='officeOfRegistrar'),
    url(r'^genericModule/', views.genericModule, name='genericModule'),
    url(r'^officeOfDeanStudents/holding_meeting', views.holdingMeeting, name='holdingMeetings'),
    url(r'^officeOfDeanStudents/meeting_Minutes', views.meetingMinutes, name='meetingMinutes'),
    url(r'^officeOfDeanStudents/hostelRoomAllotment', views.hostelRoomAllotment),
    url(r'^officeOfDeanStudents/budget_approval', views.budgetApproval),
    url(r'^officeOfDeanStudents/budget_rejection', views.budgetRejection),
    url(r'^officeOfDeanStudents/club_approval', views.clubApproval),
    url(r'^officeOfDeanStudents/club_rejection', views.clubRejection),
    url(r'^officeOfDeanStudents/budgetAllot', views.budgetAllot),
    url(r'^officeOfDeanStudents/budgetAllotEdit', views.budgetAllotEdit),
    url(r'^officeOfDeanAcademics/$', views.officeOfDeanAcademics, name='officeOfDeanAcademics'),

    url(r'^officeOfDeanAcademics/assistantship', views.assistantship, name='assistantship'),
    url(r'^officeOfDeanAcademics/formsubmit', views.formsubmit, name='formsubmit'),
    url(r'^officeOfDeanAcademics/init_assistantship', views.init_assistantship, name='init_assistantship'),
    url(r'^officeOfDeanAcademics/scholarshipform', views.scholarshipform),
    url(r'^officeOfDeanAcademics/applications', views.applications, name='applications'),
    url(r'^officeOfDeanAcademics/courses', views.courses, name='courses'),
    url(r'^officeOfDeanAcademics/scholarship', views.scholarship, name='scholarship'),
    url(r'^officeOfDeanAcademics/semresults', views.semresults, name='semresults'),
    url(r'^officeOfDeanAcademics/thesis', views.thesis, name='thesis'),
]

FusionIIIT/applications/office_module/forms.py
from django import forms
from .models import *

class Requisitionform(forms.ModelForm):
	class Meta:
		model=Requisitions
		fields=['title','department','building','description']

FusionIIIT/applications/office_module/views.py
from .models import Project_Reallocation,Project_Closure,Project_Extension,Project_Registration
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from applications.globals.models import ExtraInfo, Designation, User, HoldsDesignation
from applications.scholarships.models import Mcm
from applications.academic_procedures.models import Thesis
from applications.globals.models import HoldsDesignation
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
import datetime
from django.utils import timezone
from .forms import *
from django.db.models import Q
from .views_office_students import *
from django.shortcuts import render
from datetime import date, datetime
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import authenticate, login


def officeOfDeanRSPC(request):
    project=Project_Registration.objects.all()
    project1=Project_Extension.objects.all()
    project2=Project_Closure.objects.all()
    project3=Project_Reallocation.objects.all()

    design = HoldsDesignation.objects.filter(working=request.user)
    print(design)
    desig=[]
    for i in design:
        desig.append(str(i.designation))

    context = {'project':project, 'project1':project1, 'project2':project2, 'project3':project3, 'desig':desig}

    return render(request, "officeModule/officeOfDeanRSPC/officeOfDeanRSPC.html", context)

@login_required
def officeOfDeanPnD(request):
    user = request.user
    extrainfo = ExtraInfo.objects.get(user=user)
    requisitions=Requisitions.objects.filter(userid=extrainfo)
    holds=HoldsDesignation.objects.filter(user=user)
    civilreq=Requisitions.objects.filter(department='civil',assign_title=None)
    electricalreq = Requisitions.objects.filter(department='electrical')
    req=Requisitions.objects.all()
    deslist=['Civil_JE','Civil_AE','EE','DeanPnD','Electrical_JE','Electrical_AE']
    deslist1=['Civil_JE','Civil_AE']
    design=HoldsDesignation.objects.filter(working=user)
    desig=[]
    for i in design:
        desig.append(str(i.designation))
    print(desig)

    if 'createassign' in request.POST:
        id=request.POST.get('req_id')
        obj = Requisitions.objects.get(id=id)
        obj.assign_title = request.POST.get('title')
        obj.assign_description = request.POST.get('description')
        obj.estimate=request.FILES['estimate']
        print(obj.estimate)
        obj.assign_date=timezone.now()
        obj.save()

        for hold in holds:
            if str(hold.designation.name) in deslist1:
                if str(hold.designation.name) == "Civil_JE":
                    receive=HoldsDesignation.objects.get(designation__name="Civil_AE")
                    sent=HoldsDesignation.objects.get(designation__name="Civil_JE")
                    fdate = datetime.now().date()

                elif str(hold.designation.name)=="Electrical_JE":
                    receive=ExtraInfo.objects.get(designation__name="Electrical_AE")
                    fdate = datetime.now().date()
        moveobj=Filemovement(rid=obj,sentby=sent,receivedby=receive)
        moveobj.save()



    if 'asearch' in request.POST:
        check=request.POST.get('status')
        dept=request.POST.get('dept')
        if dept=="all":
            req=Requisitions.objects.all()
        elif dept=="civil":
            req=Requisitions.objects.filter(department='civil')
        elif dept=="electrical":
            req=Requisitions.objects.filter(department='electrical')
        if check=="1":
            req=req
        elif check=="2":
            req=req.filter(tag=0)
        elif check=="3":
            req=req.filter(tag=1)

    sentfiles=''
    for des in design:
        if str(des.designation) in deslist:
            sentfiles=Filemovement.objects.filter(Q(sentby=des)|Q(actionby_receiver='accept'))

    print(sentfiles)

    files=''
    for des in design:
        if str(des.designation) in deslist:
            files=Filemovement.objects.filter(receivedby=des,actionby_receiver='')
    allfiles=Filemovement.objects.all()

    context = {'civilreq':civilreq,'electricalreq':electricalreq,'files':files,'req':req,'sentfiles':sentfiles,'allfiles':allfiles,'requisitions':requisitions,'desig':desig}
    return render(request, "officeModule/officeOfDeanPnD/officeOfDeanPnD.html", context)


@login_required
def submitRequest(request):

    user = request.user
    extrainfo = ExtraInfo.objects.get(user=user)
    fdate = datetime.now().date()
    dept=request.POST.get('department')
    building = request.POST.get('building')
    title = request.POST.get('title')
    description = request.POST.get('description')

    request_obj = Requisitions(userid=extrainfo, req_date=fdate,
                               description=description, department=dept, title=title, building=building)
    request_obj.save()
    context={}
    return HttpResponseRedirect("/office/officeOfDeanPnD")


@login_required
def action(request):
    deslist=['Civil_JE','Civil_AE','EE','DeanPnD','Electrical_JE','Electrical_AE']
    user = request.user
    extrainfo = ExtraInfo.objects.get(user=user)
    design=HoldsDesignation.objects.filter(working=user)
    fdate = datetime.datetime.now().date()
    id=request.POST.get('select')
    fileobj=Filemovement.objects.get(pk=id)
    remarks=request.POST.get('remarks')
    sentby=''
    for des in deslist:
        try:
            sentby=HoldsDesignation.objects.get(working=user,designation__name=des)
        except :
            sentby=None

        if sentby :
            print(sentby)
            i=Designation.objects.get(name=des)
            i=i.id
            break

    reqobj=fileobj.rid

    if 'forward' in request.POST:
        fileobj.actionby_receiver="forward"
        fileobj.save()
        receive=HoldsDesignation.objects.get(designation__id=i+1)
        moveobj=Filemovement(rid=reqobj,sentby=sentby,receivedby=receive,date=fdate,remarks=remarks)
        moveobj.save()

    elif 'reject' in request.POST:
        fileobj.actionby_receiver="reject"
        fileobj.save()
        reqobj.tag=1
        reqobj.save()

    elif 'revert' in request.POST:
        fileobj.actionby_receiver="revert"
        fileobj.save()

        #   file=Requisitions.objects.get(pk=id)
        receive=HoldsDesignation.objects.get(designation__id=i-1)
        moveobj=Filemovement(rid=reqobj,sentby=sentby,receivedby=receive,date=fdate,remarks=remarks)
        moveobj.save()

    elif 'approve' in request.POST:
        fileobj.actionby_receiver="accept"
        fileobj.save()
        print(">>>>>>>>>>>>>")
        reqobj.tag=1
        reqobj.save()

    return HttpResponseRedirect("/office/officeOfDeanPnD/")


@login_required
def frequest(request):
    if request.method=='POST':
        form=Requisitionform(request.POST)
        print("hi")
    else:
        form=Requisitionform()

    return render(request,"officeModule/officeOfDeanPnD/viewRequisitions_content2.html",{'form':form})





def eisModulenew(request):
    project=Project_Registration.objects.all()
    project1=Project_Extension.objects.all()
    project2=Project_Closure.objects.all()
    project3=Project_Reallocation.objects.all()

    design = HoldsDesignation.objects.filter(working=request.user)
    print(design)
    desig=[]
    for i in design:
        desig.append(str(i.designation))

    context = {'project':project, 'project1':project1, 'project2':project2, 'project3':project3, 'desig':desig}

    return render(request, "eisModulenew/profile.html", context)



def officeOfPurchaseOfficr(request):
    return render(request, "officeModule/officeOfPurchaseOfficer/officeOfPurchaseOfficer.html", {})

def admin_reject(request):
    if request.method == "POST":
        marked = request.POST.getlist("selected")

        return HttpResponse("Done!")


def officeOfRegistrar(request):
    view = registrar_create_doc.objects.all()
    view2 = registrar_director_section.objects.all()
    view3 = registrar_establishment_section.objects.all()
    view4 = apply_for_purchase.objects.all()
    view5 = quotations.objects.all()
    general= registrar_general_section.objects.all()
    current_date = datetime.datetime.now()

    context = {"view":view,"view2":view2,"view3":view3,"view4":view4,"view5":view5, "current_date":current_date,"general":general}

    return render(request, "officeModule/officeOfRegistrar/officeOfRegistrar.html", context)


def upload(request):
    print("asdasdasdasd")
    docname = request.POST.get("docname")
    purpose = request.POST.get("purpose")
    description = request.POST.get("description")
    file = request.FILES['upload']
    print(file)
    request = registrar_create_doc(file_name=docname, purpose=purpose, Description=description, file=file)
    request.save()
    print(request)
    return HttpResponseRedirect("/office/officeOfRegistrar/")


@login_required(login_url='/accounts/login')
def officeOfHOD(request):
    pro = Teaching_credits1.objects.filter(tag=0)
    pro1 = Assigned_Teaching_credits.objects.all()
    context = {'pro':pro,'pro1':pro1}
    return render(request, "officeModule/officeOfHOD/officeOfHOD.html", context)


@login_required
def project_register(request):
    user = request.user
    extrainfo = ExtraInfo.objects.get(user=user)
    project_title = request.POST.get('project_title')
    sponsored_agency=request.POST.get('sponsored_agency')
    CO_PI = request.POST.get('copi_name')
   # start_date = datetime.strptime(request.POST.get('start_date'), "%Y-%m-%d")
    start_date = request.POST.get('start_date')
    duration = request.POST.get('duration')
    #duration = datetime.timedelta('duration')
    agreement=request.POST.get('agreement')
    amount_sanctioned = request.POST.get('amount_sanctioned')
    project_type = request.POST.get('project_type')
    remarks=request.POST.get('remarks')
    #fund_recieved_date=datetime.strptime(request.POST.get('fund_recieved_date'), "%Y-%m-%d")

FusionIIIT/templates/officeModule/officeOfDeanPnD/alerts.html
{% load static %}

{% block alerts %}
    <div class="ui centered cards" style="padding: 2px">

        {% comment %}A single card starts here!{% endcomment %}
        <div class="ui card">
            <div class="content">
                <img class="right floated circular ui image" src="{% static 'globals/img/zlatan.jpg' %}" style="width: 50px; height: auto;">
                <div class="header">
                    Pending Actions
                </div>

                <div class="meta">
                    Office Of Dean P&D
                </div>

                <div class="ui divider"></div>

                <div class="description">

                    <span>Work Assignment</span>
                    <span class="right floated">...</span>

                    <br>

                    <span>New Requisitions</span>
                    <span class="right floated">...</span>

                    <br>

                   
                </div>
            </div>

            <div class="extra content">
                <span style="color: #000;">Total Pending Actions</span>
                <span class="right floated" style="color: #000;">...</span>
            </div>
        </div>
        {% comment %}A single card starts here!{% endcomment %}

    </div>
{% endblock %}

FusionIIIT/templates/officeModule/officeOfDeanPnD/incomingFiles_content1.html
{% load static %}
{% include 'officeModule/officeOfDeanPnD/incomingFiles_content1Modal.html' %}
<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 5%;
                                                          padding-right: 5%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
    <thead>
    <tr>
        <th class="one wide column"></th>
        <th class="one wide column">
            Sr. No.
        </th>

        <th class="four wide column">
            Work Assignment ID
        </th>

        <th class="two wide column">
            Date
        </th>

        <th class="four wide column">
            Sent By
        </th>

        <th class="one wide column">
            Estimate
        </th>

        <th class="one wide column">
            Details
        </th>

        <th>
        </th>
    </tr>

    </thead>

    <tbody>
    <form action="{% url 'office:action' %}" method="POST">
        {% csrf_token %}
        {% for file in files %}
        <tr><td>
            <div class="ui radio checkbox">
                <input type="radio" name="select" value={{file.id}}><label></label>
            </div>
        </td>

            <td>
                {{forloop.counter}}
            </td>

            <td>
                {{file.rid.id}}
            </td>

            <td>
                {{file.date}}
            </td>

            <td>
                <h4 class="ui image header">
                    <img src="{% static 'globals/img/zlatan.jpg' %}" class="ui mini circular image">
                    <div class="content">
                        {{file.sentby.user.first_name}} {{file.sentby.user.last_name}}
                         <div class="sub header">
                        {% if "Civil_AE" in file.receivedby.designation.name %}
                        {{file.sentby.designation.name}}
                        {% elif "Civil_JE" in file.receivedby.designation.name %}
                        {{file.sentby.designation.name}}
                        {% elif "EE" in file.receivedby.designation.name %}
                        {{file.sentby.designation.name}}
                        {% elif "DeanPnD" in file.receivedby.designation.name %}
                        {{file.sentby.designation.name}}
                        {% elif "Director" in file.receivedby.designation.name %}
                        {{file.sentby.designation.name}}
                        {% elif "Electrical_AE" in file.receivedby.designation.name %}
                        {{file.sentby.designation.name}}
                        {% elif "Electrical_JE" in file.receivedby.designation.name %}
                        {{file.sentby.designation.name}}
                        {% endif %}
                        </div>
                        <div class="sub header">
                            {{file.sentby.user.email}}
                        </div>
                    </div>
                </h4>
            </td>

            <td>
                <!--
                 TODO: Attachments here!
                 -->

                <a class="ui inverted circular icon button" style="margin: auto;" target="_blank" href="/media/{{file.rid.estimate}}">
                    <i class="large attach black icon"></i>
                </a>
            </td>

            <td onclick="view('{{ file.pk }}')">
                <button class="ui button" type="button" id="test1">Details</button>
            </td>



        </tr>
        {% endfor %}
    </tbody>
</table>

<br>

<div class="ui divider"></div>

{% comment %}
TODO: Modal 1 and 2
{% endcomment %}

<div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">


    <div class="field">
        <label>Remarks</label>
        <textarea rows="2" name="remarks"></textarea>
    </div>

    <button class="ui red right floated button" name="reject" type="submit" value="reject">Reject</button>
    <button class="ui red right floated button" name="revert" type="submit" value="revert">Revert</button>
    <button class="ui primary right floated button" name="approve" type="submit" value="approve">Approve</button>
    <button class="ui green right floated button" name="forward" type="submit" value="forward">Forward</button>

    <br>
    <br>
</div>

</form>

<br>
<br>
<div class="ui divider"></div>

FusionIIIT/templates/officeModule/officeOfDeanPnD/incomingFiles_content2Modal.html
{% load static %}
{% block modal4 %}
<script type="text/javascript">
    function modals(a){
        var id= '.ui.modal.'+a;
        $(id).modal('show');
       }

</script>

{% for req in civilreq %}
<div class="ui modal {{ req.pk }} ">
	<div class="header">{{ req.pk }} </div>

	
   <div class="content">
   <b>Title:</b>
  {{req.title}}
  <br>
  <b>Descripton:</b>
  {{req.description}}
  </div>
		  </div>
	
             {% endfor %}
            


{% endblock %}

FusionIIIT/templates/officeModule/officeOfDeanPnD/searchAssignments_content1.html
{% load static %}
{% include 'officeModule/officeOfDeanPnD/seachAssignments_content1Modal.html' %}

<form method="POST" action="{% url 'office:officeOfDeanPnD' %}">
    {% comment %}The add a new skill Accordian starts here!{% endcomment %}
    {% csrf_token %}
    <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
        <div class="inline fields">
            <div class="field">
                <div class="ui radio checkbox">
                    <input type="radio" name="status" checked="checked" value="1">
                    <label>All</label>
                </div>
            </div>
            <div class="field">
                <div class="ui radio checkbox">
                    <input type="radio" name="status" value="2">
                    <label>Ongoing Projects</label>
                </div>
            </div>
            <div class="field">
                <div class="ui radio checkbox">
                    <input type="radio" name="status" value="3">
                    <label>Completed Projects</label>
                </div>
            </div>
        </div>
        <br>
        <div class="three fields">
            <div class="field">
                <label>From</label>
                <div class="ui calendar" id="rangestart">
                    <div class="ui input left icon">
                        <i class="calendar icon"></i>
                        <input type="text" placeholder="From">
                    </div>
                </div>
            </div>

            <div class="field">
                <label>To</label>
                <div class="ui calendar" id="rangeend">
                    <div class="ui input left icon">
                        <i class="calendar icon"></i>
                        <input type="text" placeholder="To">
                    </div>
                </div>
            </div>

            <div class="field">
                {% comment %}The Dropdown field starts here!{% endcomment %}
                <label>Department</label>

                <div class="ui fluid search selection dropdown">
                    <input name="department" type="hidden">
                    <i class="dropdown icon"></i>

                    <div class="default text">Select Department</div>

                    <div class="menu">
                        <div class="item" data-value="all">
                            All
                        </div>
                        <div class="item" data-value="civil">
                            Civil
                        </div>

                        <div class="item" data-value="electrical">
                            Electrical
                        </div>
                    </div>
                </div>
                {% comment %}The Dropdown field ends here!{% endcomment %}
            </div>
        </div>

        <div class="field">
            <button class="ui primary button right floated" type="submit" name="asearch" value="asearch">
                Search
            </button>
        </div>
    </div>
</form>

<br>
<br>
<div class="ui divider"></div>

<table class="ui very basic collapsing celled sortable table"
       style="padding-left: 10%;
                                                          padding-right: 10%;
                                                          padding-top: 1%;
                                                          padding-bottom: 1.5%;
                                                          margin: auto;">
    <thead>
    <tr>
        <th class="one wide column">
            Sr No
        </th>
        <th class="one wide column">
            Assisgnment ID
        </th>
        <th class="two wide column">
            Date Created
        </th>

        <th class="three wide column">
            Title
        </th>

        <th class="three wide column">
            Building
        </th>

        <th class="one wide column">
            Estimate
        </th>

        <th class="one wide column">
            Details
        </th>
    </tr>
    </thead>

    <tbody>
    {% for object in req%}
    <tr>

        <td>
            {{forloop.counter}}
        </td>
        <td>
            {{object.id}}
        </td>
        <td>
            {{object.assign_date}}
        </td>

        <td>
            {{object.assign_title}}
        </td>

        <td>
            {{object.building}}
        </td>

        <td>
            <a class="ui inverted huge circular icon button" target="_blank" href="/media/{{object.estimate}}"
               style="margin: auto;">
                <i class="attach black icon"></i>
            </a>

        </td>
        <td onclick="detail('{{ object.pk }}')">
            <button class="ui button" type="button" id="test">Details</button>
        </td>



    </tr>
    {% endfor %}
    </tbody>
</table>
<div class="ui divider"></div>

FusionIIIT/templates/officeModule/officeOfDeanPnD/viewRequisitions_content2.html
{% load static %}
<form action="{%url 'office:pWorkRequest' %}" method="POST">
    {% comment %}The file requiistion starts here!{% endcomment %}
    <div class="ui form" style="padding: 8px; padding-left: 24px; padding-right: 24px;">
        {% csrf_token %}


        <div class="two fields">
            <div class="six wide field">
                {% comment %}The Dropdown field starts here!{% endcomment %}
                <label>Requisition Department</label>

                <div class="ui fluid search selection dropdown">
                    <input name="department" type="hidden">
                    <i class="dropdown icon"></i>

                    <div class="default text">Select Department</div>

                    <div class="menu">
                        <div class="item" data-value="civil">
                            Civil
                        </div>
                        <div class="item" data-value="electrical">
                            Electrical
                        </div>






                    </div>
                </div>

                {% comment %}The Dropdown field ends here!{% endcomment %}
            </div>

            <div class="six wide field">
                {% comment %}The Dropdown field starts here!{% endcomment %}
                <label>Building</label>

                <div class="ui fluid search selection dropdown">
                    <input name="building" type="hidden">
                    <i class="dropdown icon"></i>

                    <div class="default text">Select Department</div>

                    <div class="menu">
                        <div class="item" data-value="cc">
                            CC
                        </div>

                        <div class="item" data-value="corelab">
                            CoreLab
                        </div>

                        <div class="item" data-value="hostel">
                            Hostel
                        </div>

                        <div class="item" data-value="lhtc">
                            LHTC
                        </div>

                        <div class="item" data-value="library">
                            Library
                        </div>


                    </div>
                </div>
                {% comment %}The Dropdown field ends here!{% endcomment %}
            </div>

        </div>


        <div class="field">
            <label>Title</label>
            <input placeholder="Title" class="ui large input" name="title">
        </div>


        <div class="field">
            <label>Description</label>
            <textarea rows="2" name="description"></textarea>
        </div>

        <div class="field">
            <button class="ui primary button right floated" type="submit">
                Submit
            </button>
        </div>
    </div>
</form>

<br>
<br>
<div class="ui divider"></div>

<!-- <form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button type="submit"></button>
</form> -->